# Generated by Django 5.1.4 on 2025-06-02 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute', '0003_alter_semester_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_type', models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical')], max_length=50)),
                ('credits', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.semester')),
            ],
            options={
                'unique_together': {('department', 'course', 'branch', 'semester', 'subject_code')},
            },
        ),
    ]
