# Generated by Django 5.1.4 on 2025-06-02 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_faculty_cbf_id'),
        ('adminportal', '0002_syllabus'),
        ('institute', '0003_alter_semester_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultySubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.admin')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.branch')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminportal.subject')),
            ],
            options={
                'ordering': ['faculty', 'subject'],
                'unique_together': {('faculty', 'subject', 'branch', 'semester', 'section')},
            },
        ),
    ]
