# Generated by Django 5.1.4 on 2025-06-02 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_faculty_cbf_id'),
        ('adminportal', '0003_facultysubjectassignment'),
        ('institute', '0003_alter_semester_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facultysubjectassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='facultysubjectassignment',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institute.course'),
        ),
        migrations.AddField(
            model_name='facultysubjectassignment',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.group'),
        ),
        migrations.AlterField(
            model_name='facultysubjectassignment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.section'),
        ),
        migrations.AlterUniqueTogether(
            name='facultysubjectassignment',
            unique_together={('faculty', 'subject', 'course', 'branch', 'semester', 'section', 'group')},
        ),
    ]
