# Generated by Django 5.1.4 on 2025-05-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_photos/'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='qualifications',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
