# Generated by Django 5.1.4 on 2025-05-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_faculty_address_faculty_dob_faculty_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='cbf_id',
            field=models.CharField(default='CBS0001', editable=False, max_length=15, unique=True),
        ),
    ]
