# Generated by Django 5.1.4 on 2025-05-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_faculty_cbf_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='cbf_id',
            field=models.CharField(editable=False, max_length=15, unique=True),
        ),
    ]
