# Generated by Django 5.1.4 on 2025-05-21 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(max_length=50)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('assigned_to', models.ManyToManyField(related_name='assigned_problems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
