# Generated by Django 5.1.4 on 2025-05-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
