# Generated by Django 5.1.4 on 2025-05-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_alter_semester_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.PositiveSmallIntegerField(help_text='Semester number (1-8)'),
        ),
    ]
