# Generated by Django 5.1.4 on 2025-05-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('semester', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=200)),
                ('program_number', models.CharField(max_length=10)),
                ('program_description', models.TextField()),
                ('branch', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
