# Generated by Django 5.1.4 on 2025-05-27 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('institute', '0003_alter_semester_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.branch'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.course'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.department'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='program_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.semester'),
        ),
    ]
